// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ99Ob_CYRIPjVmWI8AShsWrOJ_7w4stE',
    appId: '1:200801003138:web:a12800b34f9d636f22369b',
    messagingSenderId: '200801003138',
    projectId: 'flutter-upload-image-video',
    authDomain: 'flutter-upload-image-video.firebaseapp.com',
    storageBucket: 'flutter-upload-image-video.appspot.com',
    measurementId: 'G-48QLHEHQ1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClxH6jyOn64xQBbaCiVO3XjiTufbVHtqk',
    appId: '1:200801003138:android:0fad644961094c6a22369b',
    messagingSenderId: '200801003138',
    projectId: 'flutter-upload-image-video',
    storageBucket: 'flutter-upload-image-video.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3Fa_a2RrVvLQZcBQTfTLZyElWpTCawQI',
    appId: '1:200801003138:ios:5c8fa0075a3d6e3722369b',
    messagingSenderId: '200801003138',
    projectId: 'flutter-upload-image-video',
    storageBucket: 'flutter-upload-image-video.appspot.com',
    iosBundleId: 'com.example.flutterFileUploadImageVideo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3Fa_a2RrVvLQZcBQTfTLZyElWpTCawQI',
    appId: '1:200801003138:ios:502642bbb09cb97422369b',
    messagingSenderId: '200801003138',
    projectId: 'flutter-upload-image-video',
    storageBucket: 'flutter-upload-image-video.appspot.com',
    iosBundleId: 'com.example.flutterFileUploadImageVideo.RunnerTests',
  );
}
